### ISSUE TITLE
python cli initializer

### ISSUE THREAD

**Issue by uwmyuan** [tstringer/pycli#2]
Hi @trstringer 
This repo is the exact one I'm looking for. Thanks for your post and code.
It that possible to init a python cli project like `npm init` or `vue create my-project`? I found one in `nodejs` [generator-python-cmd](https://github.com/thinkulum/generator-python-cmd). It would be great if you'd like to implement a python native cli initializer.

**Comment by Jighdan** [comment]
@uwmyuan I attempted to make one [here](https://github.com/Jighdan/create-python-package). I'm not sure if it is following the best practices for creating files with Python, but you are more than welcome to contribute :-)

**Comment by uwmyuan** [comment]
@Jighdan Thanks for your effort!
